[package]
name = "live-in-backrooms"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = { version = "0.33.2", features = ["bytemuck"] }
gltf = "1.4.1"
image = { version = "0.25.10", default-features = false, features = ["hdr"] }
indextree = "4.8.1"
mikktspace = { version = "0.3.0", default-features = false, features = ["glam"] }
paste = "1.0.15"
pollster = "1.0.1"
serde = { version = "1.0.229", features = ["derive"] }
semver = "1.0.28"
toml = "1.1.4"
wgpu = "30.0.0"
winit = "0.30.13"

[dev-dependencies]
naga = "30.0.0"
